name: Manual Trigger Only

on:
  workflow_dispatch:
    inputs:
      name:
        description: "A name that does absolutely nothing"
        required: false
        type: string

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow was manually triggered, but does nothing."
